version: '3.8'
services:
  web:
    build: .
    volumes:
      - '.:/code'
    ports:
      - '8000:8000'
    restart: 'no'
    environment:
      - DEBUG=True
    command: "python3 manage.py runserver 0:8000"

  db:
    restart: 'no'