version: '3'
services:
  web:
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles

volumes:
  static_volume: