version: "3"

services:
  web:
    container_name: psave_django
    image: msworks/psave:latest
    restart: always
    env_file:
      - psave.env
    depends_on:
      - db

  db:
    container_name: psave_db
    image: postgres
    restart: always
    env_file:
      - psave.env
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: