version: "3.8"

services:
  web:
    container_name: psave_django
    image: msworks/psave:latest
    restart: always
    env_file:
      - psave.env
    depends_on:
      - db
    command: python3 ./manage.py runserver 127.0.0.1:8000
  db:
    container_name: psave_db
    image: postgres
    env_file:
      - psave.env
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: